version: "3"

services:
  namenode1:
    build: ./namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode1
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - 9870:9870
      - 9001:9001
      - 8020:8020
    volumes:
      - hadoop_namenode1:/hadoop/dfs/name
    environment:
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      HDFS_ZKFC_USER: root
      HDFS_JOURNALNODE_USER: root
      YARN_RESOURCEMANAGER_USER: root
      YARN_NODEMANAGER_USER: root
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env
  
  namenode2:
    build: ./namenode_standy
    image: bde2020/hadoop-namenode-standy:2.0.0-hadoop3.2.1-java8
    container_name: namenode2
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 100M    
    ports:
      - 9871:9870
      - 8021:8020
    volumes:
      - hadoop_namenode2:/hadoop/dfs/name
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env

  # namenode3:
  #   build: ./namenode_standy
  #   image: bde2020/hadoop-namenode-standy:2.0.0-hadoop3.2.1-java8
  #   container_name: namenode3
  #   restart: always
  #   deploy: 
  #     resources: 
  #       limits:
  #         cpus: '0.50'
  #         memory: 1000M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 100M    
  #   ports:
  #     - 9872:9870
  #     - 8082:8020
  #   volumes:
  #     - hadoop_namenode3:/hadoop/dfs/name
  #   environment:
  #     CLUSTER_NAME: test
  #     TZ: Asia/Shanghai
  #     SLAVE: 1
  #   env_file:
  #     - ./hadoop.env    
  
  journalnode1:
    build: ./journalnode
    image: bde2020/hadoop-journalnode:2.0.0-hadoop3.2.1-java8
    container_name: journalnode1
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M    
#    ports:
#      - 8485:8485
    volumes:
      - hadoop_journalnode1:/hadoop/dfs/edits
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env 
  
#   journalnode2:
#     build: ./journalnode
#     image: bde2020/hadoop-journalnode:2.0.0-hadoop3.2.1-java8
#     container_name: journalnode2
#     restart: always
#     deploy: 
#       resources: 
#         limits:
#           cpus: '0.50'
#           memory: 500M
#         reservations:
#           cpus: '0.25'
#           memory: 100M    
# #    ports:
# #      - 8485:8485
#     volumes:
#       - hadoop_journalnode2:/hadoop/dfs/edits
#     environment:
#       TZ: Asia/Shanghai
#     env_file:
#       - ./hadoop.env 

#   journalnode3:
#     build: ./journalnode
#     image: bde2020/hadoop-journalnode:2.0.0-hadoop3.2.1-java8
#     container_name: journalnode3
#     restart: always
#     deploy: 
#       resources: 
#         limits:
#           cpus: '0.50'
#           memory: 500M
#         reservations:
#           cpus: '0.25'
#           memory: 100M
# #    ports:
# #      - 8485:8485
#     volumes:
#       - hadoop_journalnode3:/hadoop/dfs/edits
#     environment:
#       TZ: Asia/Shanghai
#     env_file:
#       - ./hadoop.env 
 
  datanode1:
    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M    
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env

  # datanode2:
  #   build: ./datanode
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode2
  #   restart: always
  #   deploy: 
  #     resources: 
  #       limits:
  #         cpus: '0.50'
  #         memory: 500M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 100M    
  #   volumes:
  #     - hadoop_datanode2:/hadoop/dfs/data
  #   environment:
  #     TZ: Asia/Shanghai
  #   env_file:
  #     - ./hadoop.env 

  resourcemanager:
    build: ./resourcemanager
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M  
    ports: 
      - 8088:8088  
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env

  nodemanager:
    build: ./nodemanager
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M    
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./hadoop.env
  
  historyserver:
    build: ./historyserver
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    deploy: 
      resources: 
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M    
    ports: 
      - 19888:19888
    environment:
      TZ: Asia/Shanghai
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode1:
  hadoop_namenode2:
  hadoop_namenode3:
  hadoop_journalnode1:
  hadoop_journalnode2:
  hadoop_journalnode3:    
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:
